spring:
# DB Configuration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwh
    username: root
    password: 123456
# JPA Configuration
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
    # 最常用的属性，第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），
    # 以后加载hibernate时根据model类自动更新表结构,即使表结构改变了但表中的行仍然存在不会删除以前的行
      ddl-auto: update
  output:
    ansi:
      enabled: always

